/**
 * Published YouTube captions.
 *
 * The highest-value transcript source for third-party lessons, and the one that
 * makes the interpretation correspond to what is actually being said rather than
 * to what Polaris guessed the lesson covers. Ranks above the authored companion
 * track for exactly that reason.
 *
 * The fetch happens server-side (YouTube's caption endpoint is not CORS-readable
 * from a page), so this provider is a thin client for /api/interpreter.
 *
 * Best-effort by design. Many lessons publish no caption track, and creators can
 * disable third-party access; that is the normal case, not an error. When it
 * happens the provider declines and the chain falls through to the companion
 * track. Nothing here retries or complains.
 */

import type { TranscriptRequest, TranscriptTrack, TranscriptSegment } from "../types/transcript";
import { TranscriptUnavailableError } from "../types/transcript";
import { registerTranscriptProvider, type TranscriptProvider } from "./TranscriptProvider";
import { getMedia } from "./mediaRegistry";
import { gemmaHeaders } from "@/lib/gemma/browser-key";

type CaptionResponse = {
  cues?: Array<{ at?: number; until?: number; text?: string }>;
  language?: string;
  /** True when the only track available was machine-generated by YouTube. */
  generated?: boolean;
};

/**
 * Cached per media id, including misses.
 *
 * A miss is worth caching: without it, every language switch and every retry
 * re-requests captions for a video that has none.
 */
const cache = new Map<string, TranscriptTrack | null>();

export const YouTubeCaptionProvider: TranscriptProvider = {
  id: "youtube-captions",
  label: "Lesson captions",
  origin: "published-captions",
  // Below Polaris's own verbatim scripts, above the authored companion track:
  // real words from the lesson beat editorial notes about the lesson.
  rank: 90,
  canServe: (request: TranscriptRequest) => Boolean(getMedia(request.mediaId)?.videoId),

  getTranscript: async (request: TranscriptRequest): Promise<TranscriptTrack> => {
    const cached = cache.get(request.mediaId);
    if (cached) return cached;
    if (cached === null) throw new TranscriptUnavailableError("not-found", "youtube-captions", "No caption track for this lesson");

    const media = getMedia(request.mediaId);
    if (!media?.videoId) throw new TranscriptUnavailableError("unsupported-media", "youtube-captions");

    let payload: CaptionResponse;
    try {
      const response = await fetch("/api/interpreter", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...gemmaHeaders() },
        body: JSON.stringify({ kind: "captions", videoId: media.videoId, language: request.language ?? "en" }),
        signal: request.signal,
      });
      if (!response.ok) throw new TranscriptUnavailableError("network", "youtube-captions");
      payload = (await response.json()) as CaptionResponse;
    } catch (error) {
      if (error instanceof TranscriptUnavailableError) throw error;
      if (error instanceof DOMException && error.name === "AbortError") {
        throw new TranscriptUnavailableError("aborted", "youtube-captions");
      }
      throw new TranscriptUnavailableError("network", "youtube-captions");
    }

    const cues = (payload.cues ?? []).filter(
      (cue): cue is { at: number; until: number; text: string } =>
        typeof cue.at === "number" && typeof cue.until === "number" && typeof cue.text === "string" && cue.text.trim().length > 0,
    );

    if (cues.length === 0) {
      cache.set(request.mediaId, null);
      throw new TranscriptUnavailableError("not-found", "youtube-captions", "No caption track for this lesson");
    }

    const segments: TranscriptSegment[] = cues.map((cue, index) => ({
      id: `${request.mediaId}:yt${index}`,
      startTime: cue.at,
      endTime: cue.until,
      text: cue.text.trim(),
      language: payload.language,
      // YouTube's own auto-captions carry real timings but imperfect wording, so
      // they are trusted for alignment and flagged as lower confidence for text.
      confidence: payload.generated ? 0.7 : 1,
    }));

    const track: TranscriptTrack = {
      mediaId: request.mediaId,
      origin: "published-captions",
      language: payload.language ?? "en",
      segments,
      duration: request.duration ?? media.duration,
      providerId: "youtube-captions",
    };

    cache.set(request.mediaId, track);
    return track;
  },
};

registerTranscriptProvider(YouTubeCaptionProvider);
